apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: armycookbot
spec:
  schedule: "0 15 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: armycookbot
            image: registry.gitlab.com/btbtravis/army-cook:0.0.3
            env:
            - name: CONSUMER_KEY
              valueFrom:
                configMapKeyRef:
                  key: CONSUMER_KEY
                  name: armycook-config
            - name: CONSUMER_SECRET
              valueFrom:
                configMapKeyRef:
                  key: CONSUMER_SECRET
                  name: armycook-config
            - name: ACCESS_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: ACCESS_TOKEN
                  name: armycook-config
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                configMapKeyRef:
                  key: ACCESS_TOKEN_SECRET
                  name: armycook-config
          restartPolicy: Never
