apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: armycookbot
spec:
  schedule: "0 15 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: armycookbot
            image: registry.gitlab.com/btbtravis/army-cook:0.0.1
          restartPolicy: Never
